/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import obligatorio2p2.*;
import java.awt.*;
/**
 *
 * @author ezequiellopez
 */
public class Configuracion extends javax.swing.JFrame {
    public Aves a;
    /*
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        blankTurn.setVisible(false);
        labTurn.setVisible(false);
        this.setResizable(false);
    }
    public Configuracion(Aves ave){
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setResizable(false);
        blankTurn.setVisible(true);
        labTurn.setVisible(true);
        a=ave;
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantJug = new javax.swing.JComboBox<>();
        formaTerm = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setearConfig = new javax.swing.JButton();
        configDefecto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cantAves = new javax.swing.JTextField();
        blankTurn = new javax.swing.JTextField();
        labTurn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aves 2.0 - Configuración");
        getContentPane().setLayout(null);

        cantJug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cantJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantJugActionPerformed(evt);
            }
        });
        getContentPane().add(cantJug);
        cantJug.setBounds(66, 44, 264, 27);

        formaTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terminar turnos", "Cantidad de aves"}));
        formaTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaTermActionPerformed(evt);
            }
        });
        getContentPane().add(formaTerm);
        formaTerm.setBounds(66, 154, 264, 27);

        jLabel1.setText("Cantidad de jugadores ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(336, 48, 145, 16);

        jLabel2.setText("Cantidad de aves");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(336, 102, 107, 16);

        jLabel3.setText("Forma de terminacion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(336, 158, 137, 16);

        setearConfig.setText("Listo");
        setearConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setearConfigActionPerformed(evt);
            }
        });
        getContentPane().add(setearConfig);
        setearConfig.setBounds(6, 257, 173, 37);

        configDefecto.setText("Configuración por defecto");
        configDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configDefectoActionPerformed(evt);
            }
        });
        getContentPane().add(configDefecto);
        configDefecto.setBounds(302, 257, 179, 37);

        jLabel4.setText("Configuración");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(201, 0, 89, 16);

        cantAves.setText("20");
        cantAves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantAvesActionPerformed(evt);
            }
        });
        getContentPane().add(cantAves);
        cantAves.setBounds(66, 97, 264, 26);

        blankTurn.setText("5");
        blankTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankTurnActionPerformed(evt);
            }
        });
        getContentPane().add(blankTurn);
        blankTurn.setBounds(66, 199, 264, 26);

        labTurn.setText("Cantidad de turnos");
        getContentPane().add(labTurn);
        labTurn.setBounds(353, 204, 120, 16);

        jButton1.setText("<-Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 101, 29);

        setBounds(0, 0, 487, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void cantJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantJugActionPerformed
       
    }//GEN-LAST:event_cantJugActionPerformed

    private void setearConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setearConfigActionPerformed
        try{
        int jug=cantJug.getSelectedIndex()+2;
        int aves=Integer.parseInt((String)(cantAves.getText()));
        int tipoTerm=0;
        switch ((String)formaTerm.getSelectedItem()){
            case "Terminar turnos":
                tipoTerm=2;
                break;
            case "Cantidad de aves":
                tipoTerm=1;
                break;
        }
        int turnos=Integer.parseInt((String)blankTurn.getText());
        a.setConfig(jug, aves, tipoTerm, turnos);
        this.setVisible(false);
        }catch(Exception e){
            VentanaError v=new VentanaError("Por favor, verifica los datos ingresados");
            v.setVisible(true);
        }
        
    }//GEN-LAST:event_setearConfigActionPerformed

    private void configDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configDefectoActionPerformed
        cantJug.setSelectedItem("2");
        formaTerm.setSelectedItem("Terminar turnos");
        blankTurn.setText("5");
        cantAves.setText("20");
    }//GEN-LAST:event_configDefectoActionPerformed

    private void cantAvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantAvesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantAvesActionPerformed

    private void formaTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaTermActionPerformed
        if(formaTerm.getSelectedItem().equals("Terminar turnos")){
            blankTurn.setVisible(true);
            labTurn.setVisible(true);
        }
        else{
            blankTurn.setVisible(false);
            labTurn.setVisible(false);
        }
    }//GEN-LAST:event_formaTermActionPerformed

    private void blankTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blankTurnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blankTurn;
    private javax.swing.JTextField cantAves;
    private javax.swing.JComboBox<String> cantJug;
    private javax.swing.JButton configDefecto;
    private javax.swing.JComboBox<String> formaTerm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labTurn;
    private javax.swing.JButton setearConfig;
    // End of variables declaration//GEN-END:variables
}
