/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import java.awt.*;
import obligatorio2p2.*;
/**
 *
 * @author ezequiellopez
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public Aves a;
    public String hola;
    boolean onTop;
    public MenuPrincipal() {
        initComponents();
        this.setTitle("Aves v2.0 Beta");
        a = new Aves();
        onTop=false;
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public Aves getAves(){
        return this.a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jugar = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        config = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        diferentes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondoImg = new javax.swing.JLabel();

        jButton4.setText("Configuracion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 14, 0, 0);

        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar);
        jugar.setBounds(140, 130, 267, 29);

        registro.setText("¡Registrate!");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro);
        registro.setBounds(140, 210, 267, 29);

        config.setText("Configuración");
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        getContentPane().add(config);
        config.setBounds(140, 280, 267, 29);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        texto.setFont(new java.awt.Font("Marker Felt", 1, 48)); // NOI18N
        texto.setForeground(new java.awt.Color(0, 153, 153));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("AVES 2.0");
        getContentPane().add(texto);
        texto.setBounds(130, 10, 290, 130);

        diferentes.setText("Diferencia de nombres");
        diferentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diferentesActionPerformed(evt);
            }
        });
        getContentPane().add(diferentes);
        diferentes.setBounds(290, 330, 170, 100);

        jButton2.setText("Puntuaciones");
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 330, 170, 100);

        salir.setBackground(new java.awt.Color(255, 51, 51));
        salir.setText("Salir");
        getContentPane().add(salir);
        salir.setBounds(210, 470, 120, 29);

        fondoImg.setIcon(new javax.swing.ImageIcon("/Users/ezequiellopez/Desktop/Dibujo20140712-upside-down-bird-on-cable-national-geographic-hideta-nagai-1024x768.jpg")); // NOI18N
        getContentPane().add(fondoImg);
        fondoImg.setBounds(0, 0, 540, 500);

        setBounds(0, 0, 539, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SeleccionarJugadores sel=new SeleccionarJugadores(a);
        sel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        if(a.getConfiguracion()[0]<=a.getJugadores().size()){
            SeleccionarJugadores panel=new SeleccionarJugadores(a);
        panel.setVisible(true); 
        }else{
        VentanaError vent=new VentanaError("Por favor, revisa la configuracion");
            vent.setVisible(true);
        }
    }//GEN-LAST:event_jugarActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        RegistroJugador registro=new RegistroJugador();
        registro.setVisible(true);
    }//GEN-LAST:event_registroActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        Configuracion config=new Configuracion(a);
        config.setVisible(true);
    }//GEN-LAST:event_configActionPerformed

    private void diferentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diferentesActionPerformed
        if(!onTop){
        SelectArch dif=new SelectArch();
        dif.setVisible(true);
        onTop=true;
        }else{
            
        }
        
    }//GEN-LAST:event_diferentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton config;
    private javax.swing.JButton diferentes;
    private javax.swing.JLabel fondoImg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jugar;
    private javax.swing.JButton registro;
    private javax.swing.JButton salir;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
