package Interfaz;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import obligatorio2p2.*;

public class PanelDeJuego extends javax.swing.JFrame {

    private JButton[][] botones;
    private Tablero tablero;

    public PanelDeJuego() {
        this.initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setResizable(false);
        this.tablero = new Tablero();
        panelJuego.setLayout(new GridLayout(11, 11));
        botones = new JButton[11][11];
        for (int i = 1; i <= 10; i++) {
            for (int j = 1; j <= 10; j++) {
                JButton jButton = new JButton();
                jButton.addActionListener(new ListenerBoton(i, j));
                panelJuego.add(jButton);
                botones[i][j] = jButton;
            }
        }

        this.pintarBotones();

        botones[1][1].setBackground(Color.RED);
        botones[1][2].setBackground(Color.BLUE);
        botones[2][1].setBackground(Color.GREEN);
        botones[2][2].setBackground(Color.YELLOW);

        botones[1][3].setBackground(Color.GREEN);
        botones[1][4].setBackground(Color.YELLOW);
        botones[2][3].setBackground(Color.RED);
        botones[2][4].setBackground(Color.BLUE);
        
    }

    private void pintarBotones() {
        Color[] colores;

        for (int i = 1; i <= 10; i += 2) {
            for (int j = 1; j <= 10; j += 2) {
                colores = this.tablero.getColoresRandom();
                botones[i][j].setBackground(colores[0]);
                botones[i][j + 1].setBackground(colores[1]);
                botones[i + 1][j].setBackground(colores[2]);
                botones[i + 1][j + 1].setBackground(colores[3]);
            }
        }
    }

    private class ListenerBoton implements ActionListener {

        private int x;
        private int y;

        public ListenerBoton(int i, int j) {
// en el constructor se almacena la fila y columna que se presionó
            x = i;
            y = j;
        }

        public void actionPerformed(ActionEvent e) {
// cuando se presiona un botón, se ejecutará este método
            clickBoton(x, y);
        }
    }

    private void clickBoton(int fila, int columna) {
        //if (this.tablero.getMovimientoDisponible()) {
            if (this.tablero.getBotonesApretados() == 0) {
                this.tablero.setFila1(fila);
                this.tablero.setColumna1(columna);
                this.tablero.setBotonesApretados();
            } else {
                if (this.tablero.getBotonesApretados() == 1) {
                    this.tablero.setFila2(fila);
                    this.tablero.setColumna2(columna);
                    this.tablero.setBotonesApretados();
                    if (this.tablero.movimiento(this.botones)) {
                        this.ponerAves();
                    }
                }
            }
        //} else {
            //mensajeError.setText("No tienes movimientos disponibles");
        //}
    }

    public void ponerAves() {
        int fila1 = this.tablero.getFila1();
        int fila2 = this.tablero.getFila2();
        int columna1 = this.tablero.getColumna1();
        int columna2 = this.tablero.getColumna2();
        Color color = this.botones[fila1][columna1].getBackground();

        if (this.tablero.validarFila()) {
            for (int i = columna1; i <= columna2; i++) {
                this.botones[fila1][i].setText("X");
                this.botones[fila1][i].setBackground(color);
            }
        } else {
            for (int i = fila1; i <= fila2; i++) {
                this.botones[i][columna1].setText("X");
                this.botones[i][columna1].setBackground(color);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        avatarJugador1 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        avatarJugador2 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        avatarJugador3 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        avatarJugador4 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        getContentPane().add(panelJuego);
        panelJuego.setBounds(6, 133, 484, 422);

        avatarJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/index.png"))); // NOI18N
        avatarJugador1.setText("jLabel1");
        getContentPane().add(avatarJugador1);
        avatarJugador1.setBounds(43, 24, 74, 68);

        nombreJugador1.setText("Nombre Jugador");
        getContentPane().add(nombreJugador1);
        nombreJugador1.setBounds(31, 99, 102, 16);

        avatarJugador2.setText("jLabel1");
        getContentPane().add(avatarJugador2);
        avatarJugador2.setBounds(157, 24, 74, 68);

        nombreJugador2.setText("Nombre Jugador");
        getContentPane().add(nombreJugador2);
        nombreJugador2.setBounds(145, 99, 102, 16);

        avatarJugador3.setText("jLabel1");
        getContentPane().add(avatarJugador3);
        avatarJugador3.setBounds(265, 24, 74, 68);

        nombreJugador3.setText("Nombre Jugador");
        getContentPane().add(nombreJugador3);
        nombreJugador3.setBounds(253, 99, 102, 16);

        avatarJugador4.setText("jLabel1");
        getContentPane().add(avatarJugador4);
        avatarJugador4.setBounds(373, 24, 74, 68);

        nombreJugador4.setText("Nombre Jugador");
        getContentPane().add(nombreJugador4);
        nombreJugador4.setBounds(361, 99, 102, 16);

        setBounds(0, 0, 496, 583);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarJugador1;
    private javax.swing.JLabel avatarJugador2;
    private javax.swing.JLabel avatarJugador3;
    private javax.swing.JLabel avatarJugador4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables
}
