/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import java.awt.*;
import obligatorio2p2.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author ezequiellopez
 */
public class SeleccionarJugadores extends javax.swing.JFrame {
    private Aves aves;
    private ArrayList<Jugador> juegan;
    private ArrayList<Jugador> listaJug;    

    public SeleccionarJugadores() {
        initComponents();
        jugar.setVisible(false);
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public SeleccionarJugadores(Aves a){
        initComponents();
        this.aves=a;
        jugar.setVisible(false);
        juegan=new ArrayList();
        listaJug=new ArrayList(aves.getJugadores());
        this.jList2.setListData(this.listaJug.toArray());
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        seleccionar = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Selecciona los jugadores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 260, 16);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 40, 170, 132);

        seleccionar.setText("Seleccionar");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionar);
        seleccionar.setBounds(90, 190, 97, 29);

        jugar.setText("JUGAR");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar);
        jugar.setBounds(40, 230, 200, 60);

        jButton1.setText("<-Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 190, 90, 29);

        setBounds(0, 0, 294, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        int remover=jList2.getSelectedIndex();
        
        if(aves.getConfiguracion().length>juegan.size()){
           juegan.add((Jugador)jList2.getSelectedValue());
        }
        if (aves.getConfiguracion()[0]==juegan.size()){
            jugar.setVisible(true);
            seleccionar.setVisible(false);
        }
        listaJug.remove(remover);
        jList2.setListData(this.listaJug.toArray());
    }//GEN-LAST:event_seleccionarActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        Partida p=new Partida(aves.getConfiguracion()[0],aves.getConfiguracion()[1],aves.getConfiguracion()[2],aves.getConfiguracion()[3], juegan);
        PanelDeJuego pan=new PanelDeJuego(p);
        pan.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jugar;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
