/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import obligatorio2p2.*;

public class VentanaSiNo extends javax.swing.JFrame {

    private Partida partida;

    public VentanaSiNo(String mensaje, Partida unaPartida) {
        initComponents();
        labelMensaje.setText(mensaje);
        labelMensaje.setHorizontalAlignment(SwingConstants.CENTER);
        this.partida = unaPartida;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSi = new javax.swing.JButton();
        botonNo = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });
        getContentPane().add(botonSi);
        botonSi.setBounds(237, 109, 75, 29);

        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNo);
        botonNo.setBounds(318, 109, 75, 29);

        labelMensaje.setText("jLabel1");
        labelMensaje.setFocusable(false);
        labelMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelMensaje);
        labelMensaje.setBounds(31, 26, 338, 77);

        setBounds(0, 0, 399, 166);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        this.partida.setPartidaEnCurso(false);
        this.dispose();
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        this.partida.setPartidaEnCurso(true);
        this.dispose();
    }//GEN-LAST:event_botonNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonSi;
    private javax.swing.JLabel labelMensaje;
    // End of variables declaration//GEN-END:variables
}
